version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
    groups:
      production-deps:
        dependency-type: production
        update-types: [ minor, patch ]
      dev-deps:
        dependency-type: development
        update-types: [ minor, patch ]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3

  - package-ecosystem: nix
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
    groups:
      nix:
        patterns: ["*"]
