name: ci
on:
  push:
    branches: [main, rewrite]
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run cargo check
        run: cargo check --all-targets

      - name: Run fmt check
        run: cargo fmt --all -- --check

  clippy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run Clippy
        run: cargo clippy --all-targets

  test:
    name: test ${{ matrix.name }}
    needs: check
    continue-on-error: ${{ !matrix.required }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: linux.stable.debug
            required: true
          - name: windows
            os: windows-latest
            artifact_name: windows-msvc.stable.debug
            required: true
          - name: macos
            os: macos-latest
            artifact_name: macos.stable.debug
            required: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo nextest run --profile ci

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ./target/debug/mcdl*
            !./target/debug/mcdl.d
          retention-days: 7

  trigger-build:
    name: trigger build
    needs: [test]
    uses: ./.github/workflows/build.yml
